service: pbz-reports-service

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  role: arn:aws:iam::715075359986:role/pbz-lambda

functions:
  resolveAccountBalance:
    handler: handler.resolveAccountBalance
